//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.service.client.mainapp.ServiceFileUp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFileUp.IStreamed")]
    public interface IStreamed {
        
        // CODEGEN: 消息 FileWrapper 的包装名称(FileWrapper)以后生成的消息协定与默认值(UploadFile)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamed/UploadFile", ReplyAction="http://tempuri.org/IStreamed/UploadFileResponse")]
        common.service.client.mainapp.ServiceFileUp.Result UploadFile(common.service.client.mainapp.ServiceFileUp.FileWrapper request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamed/UploadFile", ReplyAction="http://tempuri.org/IStreamed/UploadFileResponse")]
        System.Threading.Tasks.Task<common.service.client.mainapp.ServiceFileUp.Result> UploadFileAsync(common.service.client.mainapp.ServiceFileUp.FileWrapper request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileWrapper", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileWrapper {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FilePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileData;
        
        public FileWrapper() {
        }
        
        public FileWrapper(string FilePath, System.IO.Stream FileData) {
            this.FilePath = FilePath;
            this.FileData = FileData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Result", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ReturnResult;
        
        public Result() {
        }
        
        public Result(bool ReturnResult) {
            this.ReturnResult = ReturnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStreamedChannel : common.service.client.mainapp.ServiceFileUp.IStreamed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamedClient : System.ServiceModel.ClientBase<common.service.client.mainapp.ServiceFileUp.IStreamed>, common.service.client.mainapp.ServiceFileUp.IStreamed {
        
        public StreamedClient() {
        }
        
        public StreamedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        common.service.client.mainapp.ServiceFileUp.Result common.service.client.mainapp.ServiceFileUp.IStreamed.UploadFile(common.service.client.mainapp.ServiceFileUp.FileWrapper request) {
            return base.Channel.UploadFile(request);
        }
        
        public bool UploadFile(string FilePath, System.IO.Stream FileData) {
            common.service.client.mainapp.ServiceFileUp.FileWrapper inValue = new common.service.client.mainapp.ServiceFileUp.FileWrapper();
            inValue.FilePath = FilePath;
            inValue.FileData = FileData;
            common.service.client.mainapp.ServiceFileUp.Result retVal = ((common.service.client.mainapp.ServiceFileUp.IStreamed)(this)).UploadFile(inValue);
            return retVal.ReturnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<common.service.client.mainapp.ServiceFileUp.Result> common.service.client.mainapp.ServiceFileUp.IStreamed.UploadFileAsync(common.service.client.mainapp.ServiceFileUp.FileWrapper request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<common.service.client.mainapp.ServiceFileUp.Result> UploadFileAsync(string FilePath, System.IO.Stream FileData) {
            common.service.client.mainapp.ServiceFileUp.FileWrapper inValue = new common.service.client.mainapp.ServiceFileUp.FileWrapper();
            inValue.FilePath = FilePath;
            inValue.FileData = FileData;
            return ((common.service.client.mainapp.ServiceFileUp.IStreamed)(this)).UploadFileAsync(inValue);
        }
    }
}
